### ISSUE TITLE
[Navigation Menu]

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#1]
As a **site user** there is **a functional navigation bar** so that **I can navigate easily throughout the site.**

## Acceptance Criteria

- Users can click any of the nav links and be redirected to the corresponding part of the website with no errors or broken links, and it collapses & displays as a hamburger menu on small screen sizes.

## Tasks

- [ ] Add HTML to display the nav bar and links.
- [ ] Add the correct routes in file structure.
- [ ] Display hamburger menu on mobile screens.
