### ISSUE TITLE
Github API Integration

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#10]
As a **site user** I can **see an overview of the site admin's Github statistics** in order **to see what they are currently working on and how active they are.**

## Acceptance Criteria

- Using the Github API, my personal Github statistics are visible showing my followers, repositories and stars etc along with custom styling that integrates well with the rest of the portfolio.

## Tasks

- [ ] Connect to Github API 
- [ ] Display statistics on portfolio
- [ ] Style them to fit into the sites design using Tailwind
