### ISSUE TITLE
Light/Dark Mode

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#11]
As a **site user** I can **switch between light and dark mode** so that **I can view the site in my preferable colour setting.**

## Acceptance Criteria

- There is a button in the header to switch between light and dark mode, and when pressed it adjusts the colour of the entire site while still adhering to good user experience.

## Tasks

- [x] Create custom button or swipe selector to switch between modes
- [x] Add code logic to adjust colour
- [x] Research potential library for the functionality

**Comment by dantaylor28** [comment]
Completed & closed
