### ISSUE TITLE
Animations

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#12]
As a **site user** I can **fluidly scroll through the site with the help of animations** so that **my navigation is smooth while looking attractive and modern.**

## Acceptance Criteria

- Switching between pages and scrolling down each one looks fresh and modern with components rendering onto the page with smooth, professional animations.

## Tasks

- [x] Install Framer Motion
- [x] Decide what type of animations I want and where to use them
- [x] Wrap my components in animation tags
