### ISSUE TITLE
Currently Learning Section

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#13]
In order to **see what the site admin is currently learning** as a **site visitor**, I can **see a description of any projects or languages that they are currently studying or working on.**

## Acceptance Criteria

- There is a section included in the site, with a description of what I am currently learning along with some stylish design or badges to accompany this text.

## Tasks

- [ ] Add div with currently learning description
- [ ] Potentially include some badges/images to showcase the language or framework
- [ ] Any links to the repo/project
