### ISSUE TITLE
Tools and Technologies 

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#14]
As a **site user** I can **scroll through a list of the tools and technologies that that the site admin knows** so that **I can see what experience and expertise he has in particular ones.**

## Acceptance Criteria

- There is a list of technologies present on the site that the site admin is familiar with. These should be in image form, with said image being the icon from that particular language/framework.

## Tasks

- [x] Find images for each technology I need to add
- [x] style and resize them so they fit together well
- [x] Display them in sections separated between frontend/backend and tools I use

**Comment by dantaylor28** [comment]
Completed and closed issue
