### ISSUE TITLE
Social Links

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#15]
As a **site user** I can **find clickable links that redirect me to the site admins social channels** so that **I can check them out on their social media.**

## Acceptance Criteria

- There are links present for LinkedIn and Github and these redirect the user to my personal profiles and these links open in a new tab.

## Tasks

- [x] Add anchor tags for LinkedIn & Github with the company logos as the links.
- [x] Include _blank for each
- [x] Have these links redirect the user to my personal profiles

**Comment by dantaylor28** [comment]
Completed and closed issue
