### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#16]
As a **site visitor** I can **send a question/request from a contact form on the site** so that **it is as easy as possible to get in touch with the site admin.**

## Acceptance Criteria

- There is a contact form present on the website, with an input for name, email and a text area for your question. This form should be connected up to my personal email so these questions arrive to me in real time. 

## Tasks

- [x] Create JSX for form
- [x] Link it up to my email via emailJS or something similar
- [x] Style the form so it is attractive and fits the layout of the site

**Comment by dantaylor28** [comment]
Completed & closed issue
