### ISSUE TITLE
About Me Section

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#18]
In order to **to learn more about the site admin and his experience and skills** as a **site visitor**, I can **read through the about section.**

## Acceptance Criteria

- There is an About Me section on the site, which gives some more personal information about myself along with a brief description of my skills and experience.

## Tasks

- [x] Create JSX for an About Me section 
- [x] Add a couple paragraphs of text about myself
- [x] Implement an animation on the section

**Comment by dantaylor28** [comment]
Completed & closed issue
