### ISSUE TITLE
Work Experience Section

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#20]
In order to **to gain an insight into the site admins experience** as a **site visitor**, I can **scroll through a timeline of their work experience.**

## Acceptance Criteria

- There is a timeline present on the site that lists out my work experience history in chronological order. It should give details of my role, the company and the dates that I was working there.

## Tasks

- [x] Gather info to add to this section
- [x] Include animated timeline animation similar to education section
- [x] Add custom styling to each job card

**Comment by dantaylor28** [comment]
Completed & closed issue
