### ISSUE TITLE
Downloadable CV

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#21]
As a **site visitor** I can **download a pdf of the site admins CV** so that **I can print it out and keep a hard copy of the admins details if necessary.**

## Acceptance Criteria

- There is a clickable link on the site, which opens/downloads a pdf of my CV which can be saved on the site users local machine.

## Tasks

- [ ] Create anchor link tag with a custom download cv icon
- [ ] Link my cv to the tag and ensure it opens/downloads when the link is clicked
- [ ] Ensure my CV is the current version and kept up to date

**Comment by dantaylor28** [comment]
Completed and closed issue
