### ISSUE TITLE
Typewriter Intro Text

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#22]
As a  **site visitor** I can **see an introductory text that dynamically changes** so that **I can see a clear explanation of what the site comprises of and some information about the admin.**

## Acceptance Criteria

There is a dynamic piece of text on the initial landing page that changes its content dynamically in a stylish typewriter format.

## Tasks

- [x] Install react-simple-typewriter
- [x] Define typewriter settings (typespeed, deletespeed, loop)
- [x] Define the text I want typed and then write the JSX

**Comment by dantaylor28** [comment]
Completed & closed issue
