### ISSUE TITLE
Tooltip on Tools & Technologies

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#23]
As a **site visitor** I can **hover over the displayed tools and technologies, and see a text box popup naming what that icon represents** so that **I can understand what each icon represents incase I am not familiar with a certain one.**

## Acceptance Criteria

- When hovering over all icons in the skills section, a tooltip displays for each and displays the name of the particular language/framework/tool. 

## Tasks

- [x] Create a reusable Tooltip component
- [x] Map over each tool/skill and display the text description for each 
- [x] Style the component and potentially animate it also

**Comment by dantaylor28** [comment]
Completed & closed issue
