### ISSUE TITLE
Scroll To Top 

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#27]
As a **site visitor** I can **click a button that scrolls me to the top of the viewport** so that **I can quickly and conveniently navigate through the website.**

## Acceptance Criteria

- When a user scrolls down the page, a button appears in the bottom right corner of the page that automatically scrolls the user to the top of the viewport when it is clicked.

## Tasks

- [x] Create a scroll down button that conditionally renders when a user scrolls down the page
- [x] Add an onclick to the button to scroll to viewport height 0px 
- [x] Style the button to ensure it feels in place with the sites design

**Comment by dantaylor28** [comment]
Completed & closed issue
