### ISSUE TITLE
Website Loader Animation

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#29]
As a **site visitor** I can **see a loading page animation when the website is rendering** so that **I am not staring at a blank page while the site is loading.**

## Acceptance Criteria

- When a user clicks through to my site, a full page loading animation displays while the content is rendering to the page.

## Tasks

- [ ] Research Framer Motion to see if I can create an animation using that library
- [ ] Add logic, so the animation displays when the page is loading 
- [ ] Customise the animation so it matches the overall style of my site
