### ISSUE TITLE
Carousel Displaying Data

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#30]
As a **site visitor** I can **scroll through a carousel displaying some interesting data** so that **I can see the site admin implements modern, clean ux design.**

## Acceptance Criteria

- The site contains a fully functional and bug free carousel that displays some interesting data to site visitors (potentially Github Repos)

## Tasks

- [ ] Create a responsive carousel component using tailwind css
- [ ] Add the corresponding data to each card thats included 
- [ ] Style the component for large and small screen sizes
