### ISSUE TITLE
Hero Section Background

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#31]
As a **site visitor** I can **see an eye-catching, animated background image on the hero section** so that **the page will immediately grab my attention.**

## Acceptance Criteria

- On page load, the hero section displays with an animated, eye-catching background image/design which transition when the site is switched from light/dark mode.

## Tasks

- [ ] Create or find a sleek,modern design I can use for the background
- [ ] Add a dark class for this background 
- [ ] Animate it with framer motion
