### ISSUE TITLE
QR Code CV

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#32]
As a **site visitor** I can **scan a qr code to download a copy of the site admins cv** so that **it demonstrates a unique way to showcase a document and I get to view the cv if I wish to.**

## Acceptance Criteria

- A QR code is present on the site. When it is clicked, the user is redirected to a pdf file containing my cv.

## Tasks

- [ ] Research how to create my own QR code & add it to the site.
- [ ] Link it to my cv 
- [ ] Add style ensuring it fits into the general site design
