### ISSUE TITLE
Responsive Design

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#4]
As a **site user** I can **navigate the site on various different screen sizes** so that **I am able to view it regardless of what device I am displaying it on.**

## Acceptance Criteria

- The website shifts its layout and fits on any and all screen sizes that it is viewed upon. The content of the site is dynamic and changes its position and size if displayed on larger or smaller screens.

## Tasks

- [x] Implement Tailwind classes to ensure elements are responsive.
- [x] Adjust text sizes depending on screen size. 
- [x] Add or remove components if viewed on specific screens
