### ISSUE TITLE
Project Section

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#5]
As a **site user** I can **view a selection of portfolio projects** so that **I can see what knowledge the site admin has and how that knowledge has been applied.**

## Acceptance Criteria

- There is a project section present on the site with a number of portfolio projects that the site admin has created, along with a brief description of what each one is.

## Tasks

- [x] Create project section  
- [x] List out a number of projects from Github that I have created 
- [x] Add a brief description for each, explaining what the project is

**Comment by dantaylor28** [comment]
Completed & closed Issue
