### ISSUE TITLE
Github Links

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#6]
As a **site user** I can **click on a Github link** so that **I can see a portfolio project repo in full on Github**

## Acceptance Criteria

- Each project has an accompanying Github badge linking to that projects Github repository, while that link should also open in a new tab.

## Tasks

- [x] Add anchor tag with src linking to Github repo on each project
- [x] Add _blank to each anchor tag to ensure it opens in new tab
- [x] Include clickable Github badge inside the anchor tag

**Comment by dantaylor28** [comment]
Completed and closed issue
