### ISSUE TITLE
Live Site Link

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#7]
In order to **see the functionality of each portfolio project first hand** as a **site user**, I can **click on a link to take me to the live site.**

## Acceptance Criteria

- Users can click on a link taking them to the live site of a portfolio project, ensuring that the link opens in a new tab.

## Tasks

-  [x] Add anchor tag with a src attribute linking to the live site of each project.
- [x] Add _blank to each anchor tag. 
- [x] Add custom button with text describing what happens at button execution.

**Comment by dantaylor28** [comment]
Completed and closed issue
