### ISSUE TITLE
Project Video Walkthrough 

### ISSUE THREAD

**Issue by dantaylor28** [dantaylor28/dan-taylor-portfolio#9]
As a **site visitor** I can **watch a video demonstration of each portfolio project** so that **I can see each ones capabilities without clicking into every project link.**

## Acceptance Criteria

- A short 30 second video is available to watch on every project description showcasing the basic functionality of each site. The video should play when hovered over and be muted by default.

## Tasks

- [ ] Screen record a basic run down of each portfolio project  
- [ ] Add that screen recording via a video link/ research options
- [ ] Implement autoplay on hover functionality
